/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceDeUsuario;

import Expendedora.Viaje;
import Monedas.MedioDePago;
import Monedas.Moneda;
import java.util.Collection;

/**
 *
 * @author Administrador
 */
public class MaquinaDeTickets extends javax.swing.JFrame {

    /**
     * Creates new form MaquinaDeTickets
     */
    public MaquinaDeTickets() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ciudades = new javax.swing.JTable();
        b_ficha = new javax.swing.JRadioButton();
        b_tarjeta = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        comprar = new javax.swing.JButton();
        JScroollPane1 = new javax.swing.JScrollPane();
        visor = new javax.swing.JTextArea();
        pago = new javax.swing.JTextField();
        totalCaja = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        moneda = new javax.swing.JList();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ciudades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Capital",  new Integer(25)},
                {"Godoy Cruz",  new Integer(30)},
                {"Guaymallen",  new Integer(40)},
                {"Junin",  new Integer(135)},
                {"Las Heras",  new Integer(45)},
                {"Lujan",  new Integer(70)},
                {"Maipu",  new Integer(60)},
                {"Rivadavia",  new Integer(150)},
                {"San Martin",  new Integer(120)}
            },
            new String [] {
                "Destino", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        ciudades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elijeDest(evt);
            }
        });
        jScrollPane1.setViewportView(ciudades);

        buttonGroup1.add(b_ficha);
        b_ficha.setText("Ficha");
        b_ficha.setEnabled(false);
        b_ficha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poneFicha(evt);
            }
        });

        buttonGroup1.add(b_tarjeta);
        b_tarjeta.setText("Tarjeta");
        b_tarjeta.setEnabled(false);
        b_tarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poneTarjeta(evt);
            }
        });

        jLabel2.setText("Medios de pago");

        comprar.setText("Comprar");
        comprar.setEnabled(false);
        comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comprar(evt);
            }
        });

        JScroollPane1.setBackground(new java.awt.Color(255, 255, 204));

        visor.setColumns(20);
        visor.setRows(5);
        visor.setEnabled(false);
        JScroollPane1.setViewportView(visor);

        pago.setEditable(false);
        pago.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        pago.setText("0");
        pago.setEnabled(false);

        totalCaja.setEditable(false);
        totalCaja.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        totalCaja.setText("0");
        totalCaja.setEnabled(false);

        jLabel3.setText("Pago");

        jLabel4.setText("Total caja");

        moneda.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "M10", "M25", "M50", "M5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        moneda.setEnabled(false);
        moneda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                poneMoneda(evt);
            }
        });
        jScrollPane2.setViewportView(moneda);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addGap(23, 23, 23)
                                .addComponent(b_ficha))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(comprar)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(pago, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(3, 3, 3))))
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(b_tarjeta)
                                .addGap(34, 34, 34))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(totalCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JScroollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(b_ficha)
                                    .addComponent(b_tarjeta))
                                .addGap(83, 83, 83)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comprar))))
                .addGap(18, 18, 18)
                .addComponent(JScroollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void elijeDest(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elijeDest
        desBloquear(true);
        totalCaja.setText("" + expendedor.caja.alcancia.totalizar());
        pago.setText("");
    }//GEN-LAST:event_elijeDest

    private void poneTarjeta(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poneTarjeta
        b_ficha.setEnabled(false);
        moneda.setEnabled(false);
        b_tarjeta.setEnabled(false);
        expendedor.ingresarPago(new Monedas.Tarjeta());
    }//GEN-LAST:event_poneTarjeta

    private void poneFicha(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poneFicha
        moneda.setEnabled(false);
        b_tarjeta.setEnabled(false);
        expendedor.ingresarPago(new Monedas.Ficha(100));
    }//GEN-LAST:event_poneFicha

    private void comprar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comprar
        try {
            expendedor.solicitar(expendedor.pedido());
            totalCaja.setText("" + expendedor.caja.alcancia.totalizar());
            desBloquear(false);
        }
        catch (Expendedora.ErrorDeCompra e) {}
    }//GEN-LAST:event_comprar

    private void poneMoneda(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poneMoneda
        if (moneda.isEnabled()) {
            b_ficha.setEnabled(false);
            b_tarjeta.setEnabled(false);
            String b = moneda.getSelectedValue().toString();
            Moneda unaMoneda = null;
            for (Moneda m : Moneda.getMonedas()) {
                if (m.getClass().getName().indexOf(b) >= 0) {
                    unaMoneda = m;
                    break;
                }
            }
            expendedor.ingresarPago((MedioDePago)unaMoneda.clone());
        }
    }//GEN-LAST:event_poneMoneda

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MaquinaDeTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MaquinaDeTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MaquinaDeTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MaquinaDeTickets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MaquinaDeTickets().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JScrollPane JScroollPane1;
    private static javax.swing.JRadioButton b_ficha;
    private static javax.swing.JRadioButton b_tarjeta;
    private javax.swing.ButtonGroup buttonGroup1;
    public static javax.swing.JTable ciudades;
    public static javax.swing.JButton comprar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private static javax.swing.JList moneda;
    public javax.swing.JTextField pago;
    private javax.swing.JTextField totalCaja;
    public static javax.swing.JTextArea visor;
    // End of variables declaration//GEN-END:variables

    /** Declaracion y creacion de objeto Expendedora */
    Expendedora.ExpendedoraTickets expendedor = new Expendedora.ExpendedoraTickets(this);

    /** Declaraciones de metodos auxiliares */
    public static void desBloquear(boolean si){
        b_ficha.setEnabled(si);
        moneda.setEnabled(si);
        b_tarjeta.setEnabled(si);
        comprar.setEnabled(si);
    }
}
